
import type { AutoPilotStep } from '../../lib/types'

export const intuneSteps: AutoPilotStep[] = [
  {
    id: 'intune-1-app-registrations',
    selector: '[data-testid="Microsoft_AAD_RegisteredApps"], [aria-label*="App registrations"], a[href*="RegisteredApps"], text:App-Registrierungen',
    title: 'Open App registrations',
    description: 'In the Azure portal, click on "App registrations" in the left sidebar. If you don\'t see it, use the search bar at the top.',
    waitForSelector: '.fxs-blade-content, [role="main"]',
    fallbackUrl: 'https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade',
    side: 'right',
    nerdMessage: 'First, we need to register AssetNode as an application in your Azure tenant! 🔑',
    timeout: 8000,
    autoAction: {
      type: 'navigate',
      url: 'https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade',
      logMessage: 'Navigating to App registrations',
    },
    requireConfirmation: false,
  },
  {
    id: 'intune-2-new-registration',
    selector: '[data-testid="newRegistration"], button[aria-label*="New registration"], [data-automation-id="newRegistration"], a[aria-label*="New registration"], text:Neue Registrierung, text:New registration',
    title: 'Click "New registration"',
    description: 'Click the "New registration" button at the top of the App registrations list.',
    waitForSelector: '[data-testid="newRegistration"], button[aria-label*="New registration"]',
    side: 'bottom',
    nerdMessage: 'Let\'s create a new app registration for the AssetNode integration! 🆕',
    timeout: 10000,
    autoAction: {
      type: 'click',
      selector: '[data-testid="newRegistration"], button[aria-label*="New registration"], a[aria-label*="New registration"], [data-automation-id="newRegistration"], text:Neue Registrierung, text:New registration',
      logMessage: 'Clicking "New registration" button',
    },
  },
  {
    id: 'intune-3-name-app',
    selector: 'input[aria-label*="Display name"], input[data-testid="displayName"], input[name="displayName"], input[aria-label*="Anzeigename"]',
    title: 'Name your application',
    description: 'Enter "AssetNode Intune" as the display name. Leave all other settings as default.',
    note: 'The name is just for your reference — you can change it later.',
    side: 'bottom',
    nerdMessage: 'Give it a name so your team knows what this app does! I suggest "AssetNode Intune" 📝',
    timeout: 10000,
    autoAction: {
      type: 'fill',
      selector: 'input[aria-label*="Display name"], input[aria-label*="Anzeigename"], input[aria-label*="Name" i], input[data-testid="displayName"], input[name="displayName"], .fxs-blade-content input[type="text"]:first-of-type, [role="main"] input[type="text"]:first-of-type',
      value: 'AssetNode Intune',
      logMessage: 'Entering app name: "AssetNode Intune"',
    },
  },
  {
    id: 'intune-4-register',
    selector: 'button[data-testid="registerButton"], button[type="submit"]:not([disabled]), button[aria-label*="Register"], text:Registrieren',
    title: 'Click "Register"',
    description: 'Click the "Register" button to create the application.',
    side: 'top',
    nerdMessage: 'Almost there! Hit that register button! 🚀',
    timeout: 10000,
    autoAction: {
      type: 'click',
      selector: 'button[data-testid="registerButton"], button[type="submit"]:not([disabled]), button[aria-label*="Register"], text:Registrieren',
      logMessage: 'Clicking "Register" to create the app',
    },
  },
  {
    id: 'intune-5-wait-for-app',
    selector: 'body',
    title: 'Waiting for app to be created...',
    description: 'Azure is creating your application. This usually takes a few seconds.',
    side: 'bottom',
    nerdMessage: 'Waiting for Azure to create the app... ⏳',
    timeout: 15000,
    autoAction: {
      type: 'wait',
      duration: 4000,
      logMessage: 'Waiting for app creation to complete',
    },
    requireConfirmation: false,
  },
  {
    id: 'intune-6-copy-client-id',
    selector: '[data-testid="appId"], [aria-label*="Application (client) ID"], [aria-label*="Anwendungs-ID (Client)"], .ms-TextField-field',
    title: 'Copy your Application (Client) ID',
    description: 'Copy the Application (client) ID from the overview page.',
    note: 'You can click the copy icon next to the ID.',
    side: 'bottom',
    nerdMessage: 'Grabbing the Client ID — this is key number one! 📋',
    timeout: 15000,
    autoAction: {
      type: 'copy',
      selector: 'input[aria-label*="Application (client) ID"], input[aria-label*="Anwendungs-ID (Client)"], [data-testid="appId"] input, span[data-testid="appId"]',
      credentialLabel: 'Client ID',
      logMessage: 'Copying Application (Client) ID',
    },
    requireConfirmation: false,
  },
  {
    id: 'intune-7-copy-tenant-id',
    selector: '[aria-label*="Directory (tenant) ID"], [aria-label*="Verzeichnis-ID (Mandant)"]',
    title: 'Copy your Directory (Tenant) ID',
    description: 'Copy the Directory (tenant) ID from the same overview page.',
    side: 'bottom',
    nerdMessage: 'And key number two — the Tenant ID! 📋',
    timeout: 15000,
    autoAction: {
      type: 'copy',
      selector: 'input[aria-label*="Directory (tenant) ID"], input[aria-label*="Verzeichnis-ID (Mandant)"], span[data-testid="tenantId"], [data-testid="tenantId"] input',
      credentialLabel: 'Tenant ID',
      logMessage: 'Copying Directory (Tenant) ID',
    },
    requireConfirmation: false,
  },
  {
    id: 'intune-8-certificates-secrets',
    selector: 'a[aria-label*="Certificates & secrets"], [data-testid="certificatesSecrets"], li[aria-label*="Certificates"], text:Zertifikate & Geheimnisse, text:Certificates & secrets',
    title: 'Go to Certificates & secrets',
    description: 'In the left sidebar, click on "Certificates & secrets".',
    side: 'right',
    nerdMessage: 'Now we need to create a secret key! 🔐',
    timeout: 10000,
    autoAction: {
      type: 'click',
      selector: 'a[aria-label*="Certificates & secrets"], [data-testid="certificatesSecrets"], li[aria-label*="Certificates"] a, text:Zertifikate & Geheimnisse, text:Certificates & secrets',
      logMessage: 'Navigating to Certificates & secrets',
    },
  },
  {
    id: 'intune-9-wait-for-secrets-page',
    selector: 'body',
    title: 'Loading Certificates & secrets...',
    description: 'Waiting for the page to load.',
    side: 'bottom',
    nerdMessage: 'Loading... 🔄',
    timeout: 5000,
    autoAction: {
      type: 'wait',
      duration: 2000,
      logMessage: 'Waiting for Certificates & secrets page',
    },
    requireConfirmation: false,
  },
  {
    id: 'intune-10-new-secret',
    selector: 'button[aria-label*="New client secret"], [data-testid="newClientSecret"], text:Neuer geheimer Clientschlüssel, text:New client secret',
    title: 'Click "New client secret"',
    description: 'Click "New client secret" to create a new secret.',
    side: 'bottom',
    nerdMessage: 'One more secret and we\'re golden! 🗝️',
    timeout: 10000,
    autoAction: {
      type: 'click',
      selector: 'button[aria-label*="New client secret"], [data-testid="newClientSecret"], text:Neuer geheimer Clientschlüssel, text:New client secret',
      logMessage: 'Clicking "New client secret"',
    },
  },
  {
    id: 'intune-11-add-secret',
    selector: 'button[type="submit"], button[aria-label*="Add"], button[data-testid="addSecret"], text:Hinzufügen',
    title: 'Click "Add"',
    description: 'Click the "Add" button to generate the secret.',
    side: 'bottom',
    nerdMessage: 'Generating the secret... 🎲',
    timeout: 10000,
    autoAction: {
      type: 'click',
      selector: 'button[type="submit"], button[aria-label*="Add"]:not([aria-label*="permission"]), button[data-testid="addSecret"], text:Hinzufügen',
      logMessage: 'Clicking "Add" to generate secret',
    },
  },
  {
    id: 'intune-12-wait-for-secret',
    selector: 'body',
    title: 'Secret is being generated...',
    description: 'Waiting for the secret to be generated.',
    side: 'bottom',
    nerdMessage: 'Azure is creating your secret... ⏳',
    timeout: 5000,
    autoAction: {
      type: 'wait',
      duration: 7000,
      logMessage: 'Waiting for secret generation',
    },
    requireConfirmation: false,
  },
  {
    id: 'intune-13-copy-secret',
    selector: 'body',
    title: 'Copy the client secret value',
    description: 'Copy the Value immediately — it won\'t be shown again after you leave this page.',
    note: 'IMPORTANT: Copy the "Value" column (Wert), NOT the "Secret ID". The value is only shown once!',
    side: 'bottom',
    nerdMessage: '⚠️ This is shown ONLY ONCE! Grabbing it now!',
    timeout: 15000,
    autoAction: {
      type: 'copy-clipboard',
      selector: '[data-automation-key="value"] button, [data-automation-key="value"] [role="button"], .ms-DetailsRow-cell:nth-child(3) button, [role="gridcell"]:nth-child(3) button, [aria-label*="Copy"], [aria-label*="Kopier"], [aria-label*="clipboard"], [aria-label*="Zwischenablage"], button[title*="Copy"], button[title*="Kopier"]',
      credentialLabel: 'Client Secret',
      logMessage: 'Copying Client Secret value (shown only once!)',
    },
    requireConfirmation: false,
  },
  {
    id: 'intune-14-api-permissions',
    selector: 'a[aria-label*="API permissions"], [data-testid="apiPermissions"], li[aria-label*="API permissions"], text:API-Berechtigungen, text:API permissions',
    title: 'Go to API permissions',
    description: 'In the left sidebar, click on "API permissions".',
    side: 'right',
    nerdMessage: 'Last section in Azure! Let\'s give the app the right permissions 🛡️',
    timeout: 10000,
    autoAction: {
      type: 'click',
      selector: 'a[aria-label*="API permissions"], [data-testid="apiPermissions"], li[aria-label*="API permissions"] a, text:API-Berechtigungen, text:API permissions',
      logMessage: 'Navigating to API permissions',
    },
  },
  {
    id: 'intune-15-wait-for-permissions',
    selector: 'body',
    title: 'Loading API permissions...',
    description: 'Waiting for permissions page.',
    side: 'bottom',
    nerdMessage: 'Loading... 🔄',
    timeout: 5000,
    autoAction: {
      type: 'wait',
      duration: 2000,
      logMessage: 'Waiting for API permissions page',
    },
    requireConfirmation: false,
  },
  {
    id: 'intune-16-add-permission',
    selector: 'button[aria-label*="Add a permission"], [data-testid="addPermission"], text:Berechtigung hinzufügen, text:Add a permission',
    title: 'Click "Add a permission"',
    description: 'Click "Add a permission" to open the API selector.',
    side: 'bottom',
    nerdMessage: 'We need to grant Intune device read access 📱',
    timeout: 10000,
    autoAction: {
      type: 'click',
      selector: 'button[aria-label*="Add a permission"], [data-testid="addPermission"], text:Berechtigung hinzufügen, text:Add a permission',
      logMessage: 'Clicking "Add a permission"',
    },
  },
  {
    id: 'intune-17-select-graph',
    selector: '[data-testid="microsoftGraph"], button[aria-label*="Microsoft Graph"], [aria-label="Microsoft Graph"], text:Microsoft Graph',
    title: 'Select "Microsoft Graph"',
    description: 'Click on "Microsoft Graph" to browse available permissions.',
    side: 'bottom',
    nerdMessage: 'Microsoft Graph is the API that gives us access to Intune data! 📊',
    timeout: 10000,
    autoAction: {
      type: 'click',
      selector: '[data-testid="microsoftGraph"], button[aria-label*="Microsoft Graph"], [aria-label="Microsoft Graph"], text:Microsoft Graph',
      logMessage: 'Selecting "Microsoft Graph"',
    },
  },
  {
    id: 'intune-18-application-permissions',
    selector: 'button[aria-label*="Application permissions"], [data-testid="applicationPermissions"], text:Anwendungsberechtigungen, text:Application permissions',
    title: 'Choose "Application permissions"',
    description: 'Select "Application permissions" (not "Delegated permissions").',
    note: 'Application permissions run without a signed-in user — this is what AssetNode needs for background sync.',
    side: 'bottom',
    nerdMessage: 'We need APPLICATION permissions, not delegated. This lets AssetNode sync in the background! 🔄',
    timeout: 10000,
    autoAction: {
      type: 'click',
      selector: 'button[aria-label*="Application permissions"], [data-testid="applicationPermissions"], text:Anwendungsberechtigungen, text:Application permissions',
      logMessage: 'Selecting "Application permissions"',
    },
  },
  {
    id: 'intune-19-search-permission',
    selector: 'input[aria-label*="Search"], input[placeholder*="Search"], input[type="search"], input[placeholder*="Suche"], input[aria-label*="Suche"]',
    title: 'Search for "DeviceManagementManagedDevices"',
    description: 'Type "DeviceManagementManagedDevices" in the search box.',
    side: 'bottom',
    nerdMessage: 'Search for: DeviceManagementManagedDevices.Read.All 🔍',
    timeout: 10000,
    autoAction: {
      type: 'fill',
      selector: 'input[aria-label*="Search"], input[placeholder*="Search permissions"], input[type="search"], input[placeholder*="Suche"], input[aria-label*="Suche"]',
      value: 'DeviceManagementManagedDevices',
      logMessage: 'Searching for DeviceManagementManagedDevices',
    },
  },
  {
    id: 'intune-20-expand-permission-group',
    selector: 'text:DeviceManagementManagedDevices, [aria-label*="DeviceManagementManagedDevices"]',
    title: 'Expand DeviceManagementManagedDevices group',
    description: 'Click the "DeviceManagementManagedDevices" group to expand it.',
    side: 'bottom',
    nerdMessage: 'Expanding the permission group... 📂',
    timeout: 10000,
    autoAction: {
      type: 'click',
      selector: 'text:DeviceManagementManagedDevices, [aria-label*="DeviceManagementManagedDevices"]',
      logMessage: 'Expanding DeviceManagementManagedDevices permission group',
    },
  },
  {
    id: 'intune-20b-select-permission',
    selector: 'text:DeviceManagementManagedDevices.Read.All, [aria-label*="DeviceManagementManagedDevices.Read.All"], text:Read.All',
    title: 'Select DeviceManagementManagedDevices.Read.All',
    description: 'Check the box for "DeviceManagementManagedDevices.Read.All".',
    side: 'bottom',
    nerdMessage: 'Checking the right permission box! ☑️',
    timeout: 10000,
    autoAction: {
      type: 'click',
      selector: 'text:DeviceManagementManagedDevices.Read.All, [aria-label*="DeviceManagementManagedDevices.Read.All"], text:Read.All',
      logMessage: 'Selecting DeviceManagementManagedDevices.Read.All permission',
    },
  },
  {
    id: 'intune-21-add-permissions-button',
    selector: 'button[aria-label*="Add permissions"], [data-testid="addPermissionsButton"], text:Berechtigungen hinzufügen, text:Add permissions',
    title: 'Click "Add permissions"',
    description: 'Click "Add permissions" to confirm.',
    side: 'bottom',
    nerdMessage: 'Adding the permissions! ➕',
    timeout: 10000,
    autoAction: {
      type: 'click',
      selector: 'button[aria-label*="Add permissions"], [data-testid="addPermissionsButton"], text:Berechtigungen hinzufügen, text:Add permissions',
      logMessage: 'Clicking "Add permissions" to confirm',
    },
  },
  {
    id: 'intune-22-wait-panel-close',
    selector: 'body',
    title: 'Waiting for permissions to be saved...',
    description: 'Waiting for the permissions panel to close.',
    side: 'bottom',
    nerdMessage: 'Azure is saving your permissions... ⏳',
    timeout: 5000,
    autoAction: {
      type: 'wait',
      duration: 3000,
      logMessage: 'Waiting for permissions panel to close',
    },
    requireConfirmation: false,
  },
  {
    id: 'intune-23-grant-consent',
    selector: 'button[aria-label*="Grant admin consent"], [data-testid="grantAdminConsent"], text:Administratorzustimmung, text:Grant admin consent',
    title: 'Grant admin consent',
    description: 'Click "Grant admin consent for [your organization]" and confirm.',
    note: 'You need Global Administrator or Privileged Role Administrator rights for this step.',
    side: 'bottom',
    nerdMessage: 'Final Azure step! Grant consent and you\'re done here! ✅',
    timeout: 15000,
    autoAction: {
      type: 'click',
      selector: 'button[aria-label*="Grant admin consent"], [data-testid="grantAdminConsent"], text:Administratorzustimmung, text:Grant admin consent',
      logMessage: 'Granting admin consent for the organization',
    },
  },
  {
    id: 'intune-23-done',
    selector: 'body',
    title: '🎉 Setup Complete!',
    description: 'You\'re done in Azure! The autopilot has collected your Client ID, Tenant ID, and Client Secret. Check the report to copy them into AssetNode.',
    note: 'The first device sync will start within ~10 minutes after saving in AssetNode.',
    fallbackUrl: 'https://app.asset-node.com/settings#intuneSection',
    side: 'bottom',
    nerdMessage: 'Awesome! All credentials have been collected! Check the report! 🎉🤓',
    timeout: 5000,
    requireConfirmation: false,
  },
]
