import type { ExtensionGuideStep } from '../../lib/types'

export const jamfProSteps: ExtensionGuideStep[] = [
  {
    id: 'jamf-pro-1-login',
    selector: 'body',
    title: 'Log in to Jamf Pro',
    description: 'Navigate to your Jamf Pro instance URL and sign in.',
    nerdMessage: 'Let\'s connect Jamf Pro to sync your managed devices! 🖥️',
    timeout: 5000,
  },
  {
    id: 'jamf-pro-2-settings',
    selector: 'a[href*="settings"], [data-testid="settings"], nav a:has(svg[data-icon="cog"])',
    title: 'Go to System Settings',
    description: 'Click on the gear icon or navigate to Settings.',
    side: 'right',
    nerdMessage: 'Head to System Settings to find API configuration ⚙️',
    timeout: 10000,
  },
  {
    id: 'jamf-pro-3-api-roles',
    selector: 'a[href*="apiRoles"], a[href*="api-integrations"], [data-testid="api-roles"]',
    title: 'Find API Roles and Clients',
    description: 'Under System Settings, find "API Roles and Clients".',
    side: 'right',
    nerdMessage: 'Look for "API Roles and Clients" in the settings list 🔍',
    timeout: 10000,
  },
  {
    id: 'jamf-pro-4-create-role',
    selector: 'button[aria-label*="New"], button:has(span:contains("New")), [data-testid="create-role"]',
    title: 'Create a new API role',
    description: 'Create a new API role with "Read" permissions for computer and mobile device records.',
    side: 'bottom',
    nerdMessage: 'Create a read-only role — AssetNode only needs to read device info 📖',
    timeout: 10000,
  },
  {
    id: 'jamf-pro-5-create-client',
    selector: 'button[aria-label*="New API Client"], [data-testid="create-client"]',
    title: 'Create an API client',
    description: 'Create a new API client and assign the role you just created. Copy the Client ID and Client Secret.',
    note: 'Copy the Client Secret immediately — it won\'t be shown again.',
    side: 'bottom',
    nerdMessage: '⚠️ Copy the Client Secret NOW! 📋',
    timeout: 15000,
  },
  {
    id: 'jamf-pro-6-enter-in-assetnode',
    selector: 'body',
    title: '🎉 Enter credentials in AssetNode',
    description: 'Go to AssetNode → Settings → MDM → Jamf Pro. Enter the URL, Client ID, and Client Secret.',
    fallbackUrl: 'https://app.asset-node.com/settings#jamfProSection',
    nerdMessage: 'Paste everything into AssetNode and your Jamf devices will appear! 🎉',
    timeout: 5000,
  },
]

export const jamfSchoolSteps: ExtensionGuideStep[] = [
  {
    id: 'jamf-school-1-login',
    selector: 'body',
    title: 'Log in to Jamf School',
    description: 'Navigate to your Jamf School portal and sign in.',
    nerdMessage: 'Setting up Jamf School for your education devices! 🎓',
    timeout: 5000,
  },
  {
    id: 'jamf-school-2-org-settings',
    selector: 'a[href*="organisation"], a[href*="organization"], [data-testid="org-settings"]',
    title: 'Navigate to Organisation Settings',
    description: 'Go to Organisation → Settings.',
    side: 'right',
    nerdMessage: 'Find the Organisation settings in the navigation 🏢',
    timeout: 10000,
  },
  {
    id: 'jamf-school-3-api-key',
    selector: 'button[aria-label*="Add API"], [data-testid="add-api-key"], button:has(span:contains("Add API"))',
    title: 'Create an API key',
    description: 'Click "Add API Key" and name it "AssetNode".',
    side: 'bottom',
    nerdMessage: 'Create an API key named "AssetNode" 📝',
    timeout: 10000,
  },
  {
    id: 'jamf-school-4-copy-key',
    selector: 'input[readonly], pre, code, [data-testid="api-key-value"]',
    title: 'Copy the API key',
    description: 'Copy the generated API key.',
    nerdMessage: 'Copy that key! 📋',
    timeout: 10000,
  },
  {
    id: 'jamf-school-5-enter-in-assetnode',
    selector: 'body',
    title: '🎉 Enter credentials in AssetNode',
    description: 'Go to AssetNode → Settings → MDM → Jamf School. Enter the Network ID and API key.',
    fallbackUrl: 'https://app.asset-node.com/settings#jamfSchoolSection',
    nerdMessage: 'Paste it in AssetNode and you\'re connected! 🎉',
    timeout: 5000,
  },
]
