import type { ExtensionGuideStep } from '../../lib/types'

export const personioSteps: ExtensionGuideStep[] = [
  {
    id: 'personio-1-login',
    selector: 'body',
    title: 'Log in to Personio',
    description: 'Navigate to your Personio account (yourcompany.personio.de) and sign in as an administrator.',
    nerdMessage: 'Let\'s connect your HR data from Personio! 👥',
    timeout: 5000,
  },
  {
    id: 'personio-2-settings',
    selector: 'a[href*="settings"], [data-testid="settings"], nav [aria-label*="Settings"]',
    title: 'Go to Settings',
    description: 'Click on the gear icon or "Settings" in the navigation.',
    side: 'right',
    nerdMessage: 'We need API credentials from your Personio settings ⚙️',
    timeout: 10000,
  },
  {
    id: 'personio-3-integrations',
    selector: 'a[href*="integrations"], [data-testid="integrations"], a:has(span:contains("Integrations"))',
    title: 'Open Integrations',
    description: 'Navigate to Settings → Integrations.',
    side: 'right',
    nerdMessage: 'Find the Integrations section — that\'s where the API lives 🔌',
    timeout: 10000,
  },
  {
    id: 'personio-4-api-credentials',
    selector: 'a[href*="api"], [data-testid="api-credentials"], a:has(span:contains("API"))',
    title: 'Open API Credentials',
    description: 'Click on "API Credentials" to manage your API access.',
    side: 'right',
    nerdMessage: 'We\'re looking for the API Credentials section 🔑',
    timeout: 10000,
  },
  {
    id: 'personio-5-generate',
    selector: 'button[aria-label*="Generate"], button:has(span:contains("Generate")), [data-testid="generate-credentials"]',
    title: 'Generate new credentials',
    description: 'Click "Generate new credentials" to create a new API key pair.',
    side: 'bottom',
    nerdMessage: 'Hit that Generate button! 🆕',
    timeout: 10000,
  },
  {
    id: 'personio-6-permissions',
    selector: '[data-testid="permissions"], .permissions-section, input[type="checkbox"]',
    title: 'Set API permissions',
    description: 'Grant read access to "Employees" and "Employment details". These are the minimal required scopes.',
    note: 'Only read access is needed — AssetNode never writes back to Personio.',
    side: 'bottom',
    nerdMessage: 'Just enable read access for Employees — that\'s all we need! 📖',
    timeout: 10000,
  },
  {
    id: 'personio-7-copy-credentials',
    selector: '[data-testid="client-id"], input[readonly], pre, code',
    title: 'Copy Client ID and Client Secret',
    description: 'Copy both the Client ID and Client Secret.',
    note: 'The Client Secret is only shown once — store it securely.',
    side: 'bottom',
    nerdMessage: '⚠️ Copy BOTH values! The secret won\'t be shown again! 📋',
    timeout: 15000,
  },
  {
    id: 'personio-8-enter-in-assetnode',
    selector: 'body',
    title: '🎉 Enter credentials in AssetNode',
    description: 'Go to AssetNode → Settings → HR Sync → Personio. Enter the Client ID and Client Secret, then click Save.',
    fallbackUrl: 'https://app.asset-node.com/settings#personioSection',
    nerdMessage: 'Paste them into AssetNode and your employee directory will start syncing! 🎉',
    timeout: 5000,
  },
]
